import gql from 'graphql-tag';

export default gql`mutation 
    carritoDelete
    (
        $id_producto: Int!
    ) 
    {
        carritoDelete
        (
            id_producto: $id_producto
        )
    }`;