import gql from 'graphql-tag';

export default gql`mutation 
    marcaCreate
    (
        $nombre: String,
        $id_archivo_subido_img: Int,
    ) 
    {
        marcaCreate
        (
            nombre: $nombre,
            id_archivo_subido_img: $id_archivo_subido_img
        )
        {
            id
            nombre
            id_archivo_subido_img
            __typename
        }
}`;